nelmio_api_doc:
    documentation:
        host: api.hicube.caida.org
        schemes: [https]
        info:
            title: Hi3 HTTP API
            description: Data and metadata API for the Hi3 platform.
            version: 1.0.0
        tags:
        - name: Topo
          description: Topographic data access calls
        - name: Time Series
          description: Time series data and metadata access calls
        - name: Sym
          description: URL-shortening API
        - name: Expression
          description: Expression validation, annotation and metadata access calls.
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!doc)
